//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 12:30:01 PM EEST 
//


package ua.fantotsy.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transparency" type="{http://www.example.org/SimpleTypes}integerPercentageType"/>
 *         &lt;element name="filtered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="kcal" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element ref="{http://www.example.org/Elements}castingMethod"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transparency",
    "filtered",
    "kcal",
    "castingMethod"
})
@XmlRootElement(name = "chars")
public class Chars {

    @XmlElement(required = true)
    protected String transparency;
    protected boolean filtered;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger kcal;
    @XmlElement(required = true)
    protected CastingMethod castingMethod;

    /**
     * Gets the value of the transparency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransparency() {
        return transparency;
    }

    /**
     * Sets the value of the transparency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransparency(String value) {
        this.transparency = value;
    }

    /**
     * Gets the value of the filtered property.
     * 
     */
    public boolean isFiltered() {
        return filtered;
    }

    /**
     * Sets the value of the filtered property.
     * 
     */
    public void setFiltered(boolean value) {
        this.filtered = value;
    }

    /**
     * Gets the value of the kcal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKcal() {
        return kcal;
    }

    /**
     * Sets the value of the kcal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKcal(BigInteger value) {
        this.kcal = value;
    }

    /**
     * Gets the value of the castingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CastingMethod }
     *     
     */
    public CastingMethod getCastingMethod() {
        return castingMethod;
    }

    /**
     * Sets the value of the castingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CastingMethod }
     *     
     */
    public void setCastingMethod(CastingMethod value) {
        this.castingMethod = value;
    }

}
